### ISSUE TITLE
User couldn’t figure out how to register

### ISSUE THREAD

**Issue by NorthIsUp** [django-danceschool/django-danceschool#74]
The user had issues since the “register now” button was at the top.

They also didn’t realize the the checkboxes were necessary.

Recommend that the registration button be moved to the bottom and an error message is added.

**Comment by afs2015** [comment]
We had a user email today being confused about registration because they attempted to sign up for them and a partner by checking the lead and follow box. When they did that the behavior was to refresh the page as if nothing happened and they assumed registration was broken.

I'm happy to make a seperate ticket for this issue but it seems the registration form needs:
- More validation: Situations that are not supported should display a visible error message for the user

**Comment by leetucker** [comment]
Sounds like a Bootstrap 4 CSS class issue or something similar.  There definitely used to be validation error messages if the person tried to sign up for two roles at once, or if they didn't check the boxes for anything at all.

I'll try to take a look either later today or over the weekend.  Probably an easy fix.

**Comment by leetucker** [comment]
OK, I figured out that when we switched to Bootstrap 4 and removed the unnecessary registration-related CSS, we also removed the CSS that made form errors show up in a red alert box.  The error text was still there, it was just too easy to miss.  I added back in just the CSS and classes needed to make the alert appear as it did before.

I also added a large registration button to the bottom of the page.  It's still btn-outline-secondary class (not primary), because that's less likely to create issues with different schools' templates by default, but it's there and can easily be modified by changing the template.

I'll leave this open so you can both take a look and suggest any related changes.

**Comment by afs2015** [comment]
With a button at the bottom that looks better. Validation appears to work, though it would be awesome if the "Must select only one role." could have the same top and bottom padding in the red box that pops up.

**Comment by leetucker** [comment]
Closing this issue since it seems like it has been settled.
