### ISSUE TITLE
I have some suggestions for documentation changes

### ISSUE THREAD

**Issue by ADubhlaoich** [django-danceschool/django-danceschool#85]
Hello! 

I recently pushed changes to the README (https://github.com/django-danceschool/django-danceschool/pull/84) to try simplify the text, and I think there's a lot more that could be done. Right now there's three different media that documentation for the project exists on.

- The [main website](http://django-danceschool.org/)
- The [repository](https://github.com/django-danceschool/django-danceschool)
- The [Read the Docs](http://django-danceschool.readthedocs.io/en/latest/index.html) website

The main website links to the RTD website which is being built through the /docs/ folder of the repo, but isn't ever directly mentioned in the README. Besides that, the github README has redundant information also present on the RTD website.

I think the basic requirements and installation sections of the README could be collapsed into a single, smaller section and the repo itself could be repurposed into a quick intro & set-up text, with all of the meat of the documentation and nuances of installation put onto the RTD website.

The installation process as well as the RTD pages revolving around usage seem to be half-commited to the idea that the person reading them doesn't know how to use python or has never encountered Django CMS before, which could be grand, but means that there's a lot of reading fatigue when touching each individual page.

As a result I think everything on the repo README and the RTD website could be chopped down and re-arranged, but it really depends on the target audience. The "pitch" I just rewrote in the README is also part of the main website, and as such doesn't need to be part of the base of the repo.

If there's no objections I can make a branch to refactor the whole thing.

**Comment by ADubhlaoich** [comment]
As an amendment to this proposal, I noticed that the live website isn't being served/built through the repo - which means that updating the text on it is currently impossible.

Obviously for demo purposes having a live website using django is ideal, but unless there's an actual demo section of the website people can log into, it's a null point - static content could be served from github instead, which shouldn't take much effort to reproduce since it's based on bootstrap.

**Comment by leetucker** [comment]
I'm not sure that I follow.  The URL http://django-danceschool.org/ is being served from the gh-pages branch.

**Comment by afs2015** [comment]
@leetucker, it might be worth moving the project website to a seperate github project. After work on open source projects the last few days at the PyCon 2018 sprints it seems this is a common practice.

If we want to keep it the same we should document that somewhere due to as @ADubhlaoich mentioned it's an unusual structure.

**Comment by leetucker** [comment]
@ADubhlaoich , I'm taking a pass at restructuring the documentation a bit now in preparation for the 0.6.0 release (all changes will be made in the 0.6.0-dev branch until they are ready for the release; I'm aiming for no later than next week).  I think that what I am envisioning may still be a bit longer than what you are suggesting, but it's moving in that direction.

Once that first pass is made, I'd be more than happy to have you take an additional pass at refactoring the docs.  I do want to ensure that the project is approachable to people who have little to no Python/Django experience, because I think at most schools the first person who investigates this option is likely to be someone in that position.  But if there's a way to avoid this much duplication of content, I'm all for it.

**Comment by ADubhlaoich** [comment]
@leetucker I actually pitched an idea to @afs2015 over email and forgot to bring it up here.

Could there be separate guides for each type of user on the main site?

There's naturally a big divide between those who want to contribute to the software and those who simply want to use it.

If the documentation is going to be split, then set-up and use could be part of the main website. I like readthedocs and github, but they're not pretty, and someone coming from a non-tech background might be put off.

With this approach, I think the documentation could be split into 4 user "types";

* School Administrators - Whoever's in charge of writing content for the website
* Website Administrators - Whoever's setting the website up
* Website Users - Instructors may need some form of onboarding, as would students
* Software Developers - People actually contributing to the code

I think @afs2015's earlier point of having a separate repo makes more sense with the context of people working on different parts; it'd be nonsensical having documentation or website copy clog up the commit history from a development perspective.

It might need some drastic restructuring of the website, but I can mock up a few examples for a sanity check before diving deep.

**Comment by afs2015** [comment]
@ADubhlaoich: I think this an idea that has some merit. I'm not sure the best approach but a good reference point would be [Twilio's documentation](https://www.twilio.com/docs/) which has to handle non-technical and very technical users.

**Comment by afs2015** [comment]
@ADubhlaoich: Just checking up on the status of this ticket of if we want to move forward on it or close it.

**Comment by afs2015** [comment]
Chatted with ADubhaloich on IRC and got permission to close this ticket.
